# Generated by Django 5.2.4 on 2025-07-20 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_final', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='image',
            new_name='imagen',
        ),
    ]
